apiVersion: v1
kind: Service
metadata:
  name: tkn-demo-app1
  labels:
    app: tkn-demo-app1
spec:
  selector:
    app: tkn-demo-app1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
