apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../base
images:
  - name: kind-registry:5000/tkn-demo-app1
    newTag: d551f6dbfcc7f578ba858ca2ef0e3a7d8f745a9f
patches:
  - target:
      kind: Deployment
      name: app1
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: APP_ENV
            value: uat
          - name: LOG_LEVEL
            value: info
