apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lordpangan/cnpe.git
    targetRevision: main
    path: argocd/app3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
